spring.application.name=otp-service
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/otp_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:otp_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:otp_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS:false}

logging.config=classpath:logback-spring.xml

app.jwt.secret=${APP_JWT_SECRET:111112nQ9rF5vH3jL1wRRRRRRW6aB0cD9gZ3fG7hJ5kLksfk8R1sT6uV9jjlji}
app.jwt.ttl-seconds=${APP_JWT_TTL_SECONDS:3600}
app.otp.expire-check-interval-ms=${APP_OTP_EXPIRE_CHECK_INTERVAL_MS:60000}
app.file.path=${APP_FILE_PATH:otp-codes.log}
app.mail.from=${APP_MAIL_FROM:no-reply@otp.local}
app.telegram.base-url=${APP_TELEGRAM_BASE_URL:https://api.telegram.org}
app.telegram.bot-token=${APP_TELEGRAM_BOT_TOKEN:}
app.telegram.default-chat-id=${APP_TELEGRAM_DEFAULT_CHAT_ID:}
app.smpp.host=${APP_SMPP_HOST:localhost}
app.smpp.port=${APP_SMPP_PORT:2775}
app.smpp.system-id=${APP_SMPP_SYSTEM_ID:smppclient1}
app.smpp.password=${APP_SMPP_PASSWORD:password}
app.smpp.system-type=${APP_SMPP_SYSTEM_TYPE:OTP}
app.smpp.source-addr=${APP_SMPP_SOURCE_ADDR:OTPService}
